### ISSUE TITLE
phpBB 3.2.x

### ISSUE THREAD

**Issue by Galixte** [Tatiana5/CategoriesInTabs#6]
Hi @Tatiana5,

is it possible to have this extension compatible to phpBB 3.2.x ? :)

**Comment by Tatiana5** [comment]
I do not have a time to extensions yet

**Comment by nachtelb** [comment]
Hi,
i needed 3.2.x and found the 2 changes that had to be done:
https://github.com/nachtelb/CategoriesInTabs
- new link to css
- adding class to div

**Comment by Galixte** [comment]
Thanks @nachtelb  !
